# in production this should probably be busybox, but let's use ubuntu for a
# fair comparison 
FROM tutum/ubuntu

MAINTAINER Ram Rajamony, rajamon@us.ibm.com

# RUN apt-get -qq install -y libgomp1 numactl
RUN apt-get update -y
RUN apt-get install -y apt-utils
RUN apt-get install -y libgomp1
RUN apt-get install -y numactl
# ADD bin /
CMD numactl --physcpubind=0-31 --interleave=0,1 /gups.exe
